### ISSUE TITLE
0.9.5 missing from maven central

### ISSUE THREAD

**Issue by gregsymons** [mongeez/mongeez#48]
The title says it all, as does [this search](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.mongeez%22%20AND%20a%3A%22mongeez%22).

**Comment by gregsymons** [comment]
Hmm... never mind... I misread the commit log, and thought the maven release had been run for 0.9.5, but I see there's no tag.

In which case, any idea on when we can expect a 0.9.5?

**Comment by KevinIp** [comment]
+1

**Comment by dennisa** [comment]
+1

**Comment by volyihin** [comment]
+1

**Comment by meshuga** [comment]
+1
btw. http://mvnrepository.com/artifact/com.github.volyihin/mongeez/0.9.5

**Comment by epishkin** [comment]
sorry guys. I've deployed 0.9.5 and 0.9.6 last Sunday
