### ISSUE TITLE
JavaScript change sets cannot have period in symbol in author

### ISSUE THREAD

**Issue by alexec** [mongeez/mongeez#53]
You get an error if you have a period in the author's name, e.g.:

```
//mongeez formatted javascript
//changeset alex.collins:1
db.gameConfiguration.insert({
```

Produces error:

```
java.text.ParseException: class path resource [changelog.js] has content outside of a changeset.  To start a changeset, add a comment in the format:
//changeset author:id
	at org.mongeez.reader.FormattedJavascriptChangeSetReader.parse(FormattedJavascriptChangeSetReader.java:97) ~[mongeez-0.9.4.jar:na]
```

But this is fine:

```
//changeset alex-collins:1
db.gameConfiguration.insert({
```

**Comment by patricksuter** [comment]
this works exactly as described in the [wiki] (https://github.com/secondmarket/mongeez/wiki/JavaScript-Change-Log-Format):
>  AUTHOR is the author of the changeset. CHANGEID is an identifier for the changeset. Both of these allow the letter A-Z, digits, underscores, and hyphens.

You could add support for a period by changing the following RegEx pattern in FormattedJavascriptChangeSetReader if you really need to have a period in your usernames
```java
private static final Pattern CHANGESET_PATTERN =
            Pattern.compile("//\\s*changeset\\s+([\\w\\-]+):([\\w\\-]+).*",
                    Pattern.CASE_INSENSITIVE);
```
likes this
```
change first group ([\\w\\-]+) to ([\\w\\-\\.]+)
```
